# Generated by Django 5.1.5 on 2026-05-14 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_prices',
            new_name='total_price',
        ),
    ]
